name: translate_mobile
description: Translator mobile app
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.9.0 <4.0.0"   # <-- lower-bound + upper-bound; fixes your error

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.0
  dio_cookie_manager: ^3.1.1
  cookie_jar: ^4.0.8
  path_provider: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
